/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dwm.a2;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        
    }
}
